--
-- Script was generated by Devart dbForge Studio 2020 for PostgreSQL, Version 2.3.278.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 23.10.2021 7:57:06
-- Server version: PostgreSQL 14.0
--


INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(1, E'Acura');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(2, E'Alfa Romeo');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(3, E'Aston Martin');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(4, E'Audi');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(5, E'Bentley');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(6, E'BMW');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(7, E'Brilliance');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(8, E'Bugatti');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(9, E'Buick');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(10, E'BYD');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(11, E'Cadillac');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(12, E'Changan');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(13, E'Chery');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(14, E'Chevrolet');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(15, E'Chrysler');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(16, E'Citroen');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(17, E'Dacia');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(18, E'Daewoo');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(19, E'Daihatsu');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(20, E'Datsun');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(21, E'Dodge');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(22, E'Dongfeng');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(23, E'FAW');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(24, E'Ferrari');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(25, E'Fiat');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(26, E'Fisker');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(27, E'Ford');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(28, E'Foton');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(29, E'GAC');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(30, E'GAZ');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(31, E'Geely');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(32, E'Genesis');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(33, E'GMC');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(34, E'Great Wall');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(35, E'Haval');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(36, E'Holden');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(37, E'Honda');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(38, E'Hummer');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(39, E'Hyundai');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(40, E'Infiniti');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(41, E'Isuzu');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(42, E'Iveco');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(43, E'Jac');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(44, E'Jaguar');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(45, E'Jeep');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(46, E'Kia');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(47, E'Lamborghini');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(48, E'Lancia');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(49, E'Land Rover');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(50, E'Lexus');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(51, E'Lifan');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(52, E'Lincoln');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(53, E'Lotus');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(54, E'Marussia');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(55, E'Maserati');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(56, E'Maybach');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(57, E'Mazda');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(58, E'McLaren');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(59, E'Mercedes');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(60, E'Mercury');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(61, E'MG');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(62, E'Mini');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(63, E'Mitsubishi');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(64, E'Nissan');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(65, E'Noble');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(66, E'Opel');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(67, E'Peugeot');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(68, E'Plymouth');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(69, E'Pontiac');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(70, E'Porsche');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(71, E'Ravon');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(72, E'Renault');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(73, E'Rolls-Royce');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(74, E'Rover');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(75, E'Saab');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(76, E'Saturn');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(77, E'Scion');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(78, E'Seat');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(79, E'Skoda');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(80, E'Smart');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(81, E'Ssang Yong');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(82, E'Subaru');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(83, E'Suzuki');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(84, E'Tesla');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(85, E'Toyota');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(86, E'UAZ');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(87, E'VAZ');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(88, E'Volkswagen');
INSERT INTO "autoserviceDB".public."Brands"("Id", "BrandName") VALUES
(89, E'Volvo');