--
-- Script was generated by Devart dbForge Studio 2020 for PostgreSQL, Version 2.3.278.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 23.10.2021 7:57:08
-- Server version: PostgreSQL 14.0
--


INSERT INTO "autoserviceDB".public."__EFMigrationsHistory"("MigrationId", "ProductVersion") VALUES
(E'20211020143959_InitialCreate', E'5.0.11');